### PR TITLE
Ensure that predictions/tallies are always deterministic

### PR DESCRIPTION
**Pull request by timkaye11**
This PR fixes a bug in the categorial-ballot-box where predictions were not deterministic if there was a "tie". 

For instance, if we have 10 trees in our forest, and if 5 trees voted for "1" and 5 trees voted for "2", that would constitute a tie. We should be deterministic about picking the winner (either always choose "1" or always choose "2"), but the ordering of the "range" operator in Go (when applied to maps)  is non-deterministic, so depending on the order of this line (https://github.com/lytics/CloudForest/blob/master/catballotbox.go#L58), the winner can vary, and therefore, the error-rates can vary. 

also cleans up some `math/rand` stuff

### CODE REVIEW

**Comment by glycerine** [comment]
Thanks Tim. I think my simultaneous effort over at https://github.com/ryanbressler/CloudForest/pull/64 might be simpler and faster--no sort call needed--but the two pulls aren't completely overlapping, and sorting may have advantages I'm unaware of.

**Comment by drewlanenga** [comment]
Hm, random forests are inherently random &mdash; hello bootstrapping!  Call me crazy, but I'm not against keeping the current implementation where tie breaking is performed as a by-product of the `range` operator's randomness.

If we do want a more stable mechanism for tie breaking, I'm not sure we should "be deterministic about picking a winner" &mdash; at least in the sense of deterministically picking a winner based on the _value_ of the _label_, rather than about some other heuristic from the actual model.

Looking over the [original paper](https://link.springer.com/content/pdf/10.1023%2FA%3A1010933404324.pdf), ties don't explicitly come up, but some of the Adaboost conjecturing suggests that a _weighted_ majority vote, where weights are based on something like OOB error, might provide a more stable mechanism for picking labels in the event of ties.  (Although that potentially overcomplicates things by performing different tie-breaking during model building and prediction...)

**Comment by glycerine** [comment]
Haha. Yes, if it was truly random, that might be a feature to have under flag. But I want my predictor to always produce the same prediction when fed the same data. That is very, very important for reproducibility of research. That's a critical notion which outweighs all other concerns.

addendum: Moreover, it's really hard to maintain software in the face of flakey tests that fail occasionally; e.g. only every 1 in 7 runs as we had here.

**Comment by timkaye11** [comment]
Good point @glycerine  - IMO unit tests should consistently pass/fail, and I think it's weird to have the same model output different error-rates and predictions to begin with.

**Comment by drewlanenga** [comment]
Yep, great points all around. 😄

I'm definitely in favor of the idea that, _for a given model, the same inputs should yield consistent outputs_.  Reproducible research and reliable testing are goals that I'm also in favor of.

(What I don't necessarily support is the idea that _for a given data set, the same model configuration should yield an identical model_.  Not to be coy, but if we're looking for a model that builds deterministically, we shouldn't use one that inherently bootstraps, right?)

My only concern was that a tie between two categories/labels shouldn't be determined by the value of the labels themselves, but the "strength" of the tree from which it came.

It seems like [modifying how the tree votes](https://github.com/lytics/CloudForest/blob/1b898b2d686eadcc69bc01c6e85b698e9642ae5f/tree.go#L412), by incorporating OOB error or something, would be favorable.  Although we'd probably want to only weight votes in the event of a tie, so as to not diverge from the original implementation too much?  Maybe it's worth checking how R's [randomForest](https://cran.r-project.org/package=randomForest) package handles ties.

All that said, I'm happy to be outvoted.  It seems like a corner case that has yet to give us any serious problems.

**Comment by glycerine** [comment]
Well, distinguish between training and deployment. Randomness during model training is useful. Once the model is built, a deployed model being tested should reproduce the same output given the same input.

This is really a minor change. Ties on practical data sets grows exponentially less likely, with each additional data row. We only hit the bug in the first place on the small data sets (Iris, Boston) used for the unit tests.  Moreover we are simply fixing what was happening anyway 90% of the time to make it happen 100% of the time.

**Review by drewlanenga — APPROVED** [review]

**Comment by glycerine** [comment]
err, I'm not sure this logic is correct actually... because maxVote will change as the map iteration goes along, the `ties` slice could end up with entries from values that were tied earlier in the iteration, but then later beaten out. So this tie breaking logic could result in choosing ultimately a winner that was not tied for best place.

~~~
    for k, v := range bb.Box[i].Map {
        if v > maxVote {
            predictedn = k
            maxVote = v
            ties = nil
        }

        // keep track of the ties so that our predictions
        // are deterministic
        if v == maxVote {
            ties = append(ties, k)
        }
    }
~~~

update: Oh wait. This does set `ties = nil` when a new max is found.  Okay. I think this is correct then. I withdraw the objection.

**Comment by timkaye11** [comment]
@glycerine haha you had me worried so I started to write some test cases https://play.golang.org/p/kT3x6lMiuTL

**Comment by glycerine** [comment]
@timkaye11 lol... sorry about that!

**Pull request merged**
